In [16]:
import pandas as pd
import numpy as np 
data = pd.read_csv("thanksgiving.csv",encoding="Latin-1")
data.head(5)

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific

In [4]:
data.columns

Index(['RespondentID', 'Do you celebrate Thanksgiving?',
       'What is typically the main dish at your Thanksgiving dinner?',
       'What is typically the main dish at your Thanksgiving dinner? - Other (please specify)',
       'How is the main dish typically cooked?',
       'How is the main dish typically cooked? - Other (please specify)',
       'What kind of stuffing/dressing do you typically have?',
       'What kind of stuffing/dressing do you typically have? - Other (please specify)',
       'What type of cranberry saucedo you typically have?',
       'What type of cranberry saucedo you typically have? - Other (please specify)',
       'Do you typically have gravy?',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Brussel sprouts',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Carrots',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cauliflower',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Corn',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cornbread',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Fruit salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Green beans/green bean casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Macaroni and cheese',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Mashed potatoes',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Rolls/biscuits',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Squash',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Vegetable salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Yams/sweet potato casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Buttermilk',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Cherry',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Chocolate',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Coconut cream',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Key lime',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Peach',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Sweet Potato',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - None',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Apple cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Blondies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Brownies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Carrot cake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cheesecake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cookies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Fudge',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Ice cream',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Peach cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - None',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify)',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify).1',
       'Do you typically pray before or after the Thanksgiving meal?',
       'How far will you travel for Thanksgiving?',
       'Will you watch any of the following programs on Thanksgiving? Please select all that apply. - Macy's Parade',
       'What's the age cutoff at your "kids' table" at Thanksgiving?',
       'Have you ever tried to meet up with hometown friends on Thanksgiving night?',
       'Have you ever attended a "Friendsgiving?"',
       'Will you shop any Black Friday sales on Thanksgiving Day?',
       'Do you work in retail?',
       'Will you employer make you work on Black Friday?',
       'How would you describe where you live?', 'Age', 'What is your gender?',
       'How much total combined money did all members of your HOUSEHOLD earn last year?',
       'US Region'],
      dtype='object')

In [5]:
data["Do you celebrate Thanksgiving?"].value_counts()

Yes    980
No      78
Name: Do you celebrate Thanksgiving?, dtype: int64

In [6]:
data_yes = data[data["Do you celebrate Thanksgiving?"]=="Yes"]
data_yes["Do you celebrate Thanksgiving?"].value_counts()

Yes    980
Name: Do you celebrate Thanksgiving?, dtype: int64

In [7]:
data_yes["What is typically the main dish at your Thanksgiving dinner?"].value_counts()

Turkey                    859
Other (please specify)     35
Ham/Pork                   29
Tofurkey                   20
Chicken                    12
Roast beef                 11
I don't know                5
Turducken                   3
Name: What is typically the main dish at your Thanksgiving dinner?, dtype: int64

In [8]:
Tofurkey = data["What is typically the main dish at your Thanksgiving dinner?"]=="Tofurkey"
print(data[Tofurkey]["Do you typically have gravy?"])

4      Yes
33     Yes
69      No
72      No
77     Yes
145    Yes
175    Yes
218     No
243    Yes
275     No
393    Yes
399    Yes
571    Yes
594    Yes
628     No
774     No
820     No
837    Yes
860     No
953    Yes
Name: Do you typically have gravy?, dtype: object

In [9]:
apple_isnull = pd.isnull(data["Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple"])
pumpkin_isnull = pd.isnull(data["Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin"])
pecan_isnull = pd.isnull(data["Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan"])
ate_pies = apple_isnull & pumpkin_isnull & pecan_isnull
print(ate_pies.value_counts())

False    876
True     182
dtype: int64

In [20]:
def StoI(value) :
    if pd.isnull(value) :
        return None
    first_value = value.split(' ')[0]
    refine_value = first_value.replace('+','')
    return int(refine_value)

data["int_age"] = data["Age"].apply(StoI)
data["int_age"].describe()

count    1025.000000
mean       39.383415
std        15.398493
min        18.000000
25%        30.000000
50%        45.000000
75%        60.000000
max        60.000000
Name: int_age, dtype: float64

In [28]:
def StoI2(value) :
    if pd.isnull(value) :
        return None
    first_value = value.split(' ')[0]
    if first_value == "Prefer" :
        return None
    first_value = first_value.replace('$','')
    first_value = first_value.replace(',','')
    return int(first_value)

data["int_income"] = data["How much total combined money did all members of your HOUSEHOLD earn last year?"].apply(StoI2)
data["int_income"].describe()

count       889.000000
mean      74077.615298
std       59360.742902
min           0.000000
25%       25000.000000
50%       50000.000000
75%      100000.000000
max      200000.000000
Name: int_income, dtype: float64

# Findings
I can't find something special. Just I infer that these data are distributed very evenly as watching mean and stdard deviation value.

In [12]:
data["How far will you travel for Thanksgiving?"].value_counts()

Thanksgiving is happening at my home--I won't travel at all                         396
Thanksgiving is local--it will take place in the town I live in                     276
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    197
Thanksgiving is out of town and far away--I have to drive several hours or fly       82
Name: How far will you travel for Thanksgiving?, dtype: int64

In [13]:
data[data["int_income"] < 150000]["How far will you travel for Thanksgiving?"].count()
low_far = data[data["int_income"] < 150000]["How far will you travel for Thanksgiving?"]
low_far_valc = low_far.value_counts()
low_far_per = low_far_valc/low_far_valc.sum() * 100
print(low_far_per)

Thanksgiving is happening at my home--I won't travel at all                         40.783745
Thanksgiving is local--it will take place in the town I live in                     29.462990
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    21.770682
Thanksgiving is out of town and far away--I have to drive several hours or fly       7.982583
Name: How far will you travel for Thanksgiving?, dtype: float64

In [14]:
over_far = data[data["int_income"]>150000]["How far will you travel for Thanksgiving?"].value_counts()
over_far_per = over_far/over_far.sum()*100
print(over_far_per)

Thanksgiving is happening at my home--I won't travel at all                         48.039216
Thanksgiving is local--it will take place in the town I live in                     24.509804
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    15.686275
Thanksgiving is out of town and far away--I have to drive several hours or fly      11.764706
Name: How far will you travel for Thanksgiving?, dtype: float64

# Findings
People who have income over 150000 and don't plan to go out far in Thanksgiving is more than people who have income under 150000 and have same plan.

In [22]:
data.pivot_table(index=["Have you ever tried to meet up with hometown friends on Thanksgiving night?"], columns=['Have you ever attended a "Friendsgiving?"'],values="int_age",aggfunc=np.mean)

Have you ever attended a "Friendsgiving?"                  No        Yes
Have you ever tried to meet up with hometown fr...
No                                                  42.283702  37.010526
Yes                                                 41.475410  33.976744

In [29]:
 data.pivot_table(index=["Have you ever tried to meet up with hometown friends on Thanksgiving night?"],columns=['Have you ever attended a "Friendsgiving?"'],values="int_income")

Have you ever attended a "Friendsgiving?"                     No           Yes
Have you ever tried to meet up with hometown fr...
No                                                  78914.549654  72894.736842
Yes                                                 78750.000000  66019.736842

# Findings
Young people who are under 40 seem to have tried to be positive to meet up with friends and attend "Friends giving" more than Older people.

People who earn lower income are positive to attend "Friendsgiving" and meet up with hometown frindes on Thanksgiving night.

## Recommended steps
- Figure out the most common dessert people eat.

In [44]:
desserts = ["Apple cobbler", "Blondies", "Brownies", "Carrot cake", "Cheesecake", "Cookies", "Fudge", "Ice cream", "Peach cobbler"]
question = "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - "

max_value = int()
for dessert in desserts :
    ask_que = question + dessert
    value = data[ask_que].value_counts().values[0]
    if not max_value :
        max_value_dessert = dessert
    else :
        if max_value < value :
            max_value_dessert = desset

print(dessert)

Peach cobbler

- Figure out the most common complete meal people eat.

In [50]:
data["What is typically the main dish at your Thanksgiving dinner?"].value_counts()

Turkey                    859
Other (please specify)     35
Ham/Pork                   29
Tofurkey                   20
Chicken                    12
Roast beef                 11
I don't know                5
Turducken                   3
Name: What is typically the main dish at your Thanksgiving dinner?, dtype: int64

- Identify how many people work on Thanksgiving.

In [53]:
data["Will you employer make you work on Black Friday?"].value_counts()

Yes              43
No               20
Doesn't apply     7
Name: Will you employer make you work on Black Friday?, dtype: int64

- Find regional patterns in the dinner menus.

In [60]:
data["int_dinner"] = 1
data.pivot_table(index="US Region", columns="What is typically the main dish at your Thanksgiving dinner?", values="int_dinner", aggfunc=np.sum)

What is typically the main dish at your Thanksgiving dinner?,Chicken,Ham/Pork,I don't know,Other (please specify),Roast beef,Tofurkey,Turducken,Turkey
US Region,,,,,,,,
East North Central,NaN,4.0,NaN,5.0,NaN,1.0,NaN,135.0
East South Central,NaN,1.0,NaN,4.0,1.0,NaN,NaN,50.0
Middle Atlantic,1.0,2.0,NaN,4.0,2.0,5.0,1.0,130.0
Mountain,1.0,1.0,NaN,NaN,NaN,2.0,NaN,37.0
New England,2.0,NaN,NaN,1.0,NaN,1.0,NaN,51.0
Pacific,NaN,6.0,1.0,9.0,1.0,4.0,2.0,107.0
South Atlantic,3.0,7.0,NaN,6.0,3.0,3.0,NaN,181.0
West North Central,1.0,4.0,1.0,3.0,NaN,2.0,NaN,60.0
West South Central,1.0,2.0,NaN,3.0,NaN,2.0,NaN,77.0

- Find age, gender, and income based patterns in dinner menus.

In [61]:
data.pivot_table(index=["Age","What is your gender?","int_income"], columns = "What is typically the main dish at your Thanksgiving dinner?", values="int_dinner",aggfunc=np.sum)

What is typically the main dish at your Thanksgiving dinner?  Chicken  \
Age     What is your gender? int_income
18 - 29 Female               0.0                                  NaN
                             10000.0                              NaN
                             25000.0                              NaN
                             50000.0                              NaN
                             75000.0                              NaN
                             100000.0                             NaN
                             125000.0                             NaN
                             150000.0                             NaN
                             175000.0                             NaN
                             200000.0                             NaN
        Male                 0.0                                  1.0
                             10000.0                              1.0
                             25000.0                              NaN
                             50000.0                              NaN
                             75000.0                              NaN
                             100000.0                             NaN
                             125000.0                             NaN
                             150000.0                             NaN
                             200000.0                             NaN
30 - 44 Female               0.0                                  1.0
                             10000.0                              NaN
                             25000.0                              1.0
                             50000.0                              NaN
                             75000.0                              NaN
                             100000.0                             NaN
                             125000.0                             NaN
                             150000.0                             NaN
                             175000.0                             NaN
                             200000.0                             NaN
        Male                 0.0                                  NaN
...                                                               ...
45 - 59 Male                 0.0                                  NaN
                             10000.0                              NaN
                             25000.0                              NaN
                             50000.0                              NaN
                             75000.0                              NaN
                             100000.0                             NaN
                             125000.0                             NaN
                             150000.0                             NaN
                             175000.0                             NaN
                             200000.0                             NaN
60+     Female               0.0                                  NaN
                             10000.0                              NaN
                             25000.0                              NaN
                             50000.0                              NaN
                             75000.0                              NaN
                             100000.0                             NaN
                             125000.0                             NaN
                             150000.0                             NaN
                             175000.0                             NaN
                             200000.0                             NaN
        Male                 0.0                                  NaN
                             10000.0                              NaN
                             25000.0                              2.0
                             50000.0                              NaN
                             75000.0                              NaN
                             100000.0                             NaN
                             125000.0                             NaN
                             150000.0                             NaN
                             175000.0                             NaN
                             200000.0                             1.0

What is typically the main dish at your Thanksgiving dinner?  Ham/Pork  \
Age     What is your gender? int_income
18 - 29 Female               0.0                                   NaN
                             10000.0                               1.0
                             25000.0                               NaN
                             50000.0                               NaN
                             75000.0                               NaN
                             100000.0                              1.0
                             125000.0                              NaN
                             150000.0                              NaN
                             175000.0                              NaN
                             200000.0                              NaN
        Male                 0.0                                   1.0
                             10000.0                               NaN
                             25000.0                               1.0
                             50000.0                               NaN
                             75000.0                               NaN
                             100000.0                              NaN
                             125000.0                              NaN
                             150000.0                              NaN
                             200000.0                              1.0
30 - 44 Female               0.0                                   NaN
                             10000.0                               2.0
                             25000.0                               1.0
                             50000.0                               NaN
                             75000.0                               2.0
                             100000.0                              NaN
                             125000.0                              NaN
                             150000.0                              NaN
                             175000.0                              NaN
                             200000.0                              1.0
        Male                 0.0                                   NaN
...                                                                ...
45 - 59 Male                 0.0                                   NaN
                             10000.0                               NaN
                             25000.0                               1.0
                             50000.0                               1.0
                             75000.0                               1.0
                             100000.0                              1.0
                             125000.0                              NaN
                             150000.0                              NaN
                             175000.0                              NaN
                             200000.0                              NaN
60+     Female               0.0                                   NaN
                             10000.0                               NaN
                             25000.0                               NaN
                             50000.0                               NaN
                             75000.0                               2.0
                             100000.0                              NaN
                             125000.0                              NaN
                             150000.0                              NaN
                             175000.0                              NaN
                             200000.0                              NaN
        Male                 0.0                                   NaN
                             10000.0                               NaN
                             25000.0                               NaN
                             50000.0                               NaN
                             75000.0                               NaN
                             100000.0                              NaN
                             125000.0                              NaN
                             150000.0                              NaN
                             175000.0                              NaN
                             200000.0                              NaN

What is typically the main dish at your Thanksgiving dinner?  I don't know  \
Age     What is your gender? int_income
18 - 29 Female               0.0                                       NaN
                             10000.0                                   NaN
                             25000.0                                   NaN
                             50000.0                                   1.0
                             75000.0                                   NaN
                             100000.0                                  NaN
                             125000.0                                  NaN
                             150000.0                                  NaN
                             175000.0                                  NaN
                             200000.0                                  NaN
        Male                 0.0                                       1.0
                             10000.0                                   NaN
                             25000.0                                   NaN
                             50000.0                                   NaN
                             75000.0                                   NaN
                             100000.0                                  NaN
                             125000.0                                  NaN
                             150000.0                                  NaN
                             200000.0                                  NaN
30 - 44 Female               0.0                                       NaN
                             10000.0                                   NaN
                             25000.0                                   NaN
                             50000.0                                   NaN
                             75000.0                                   NaN
                             100000.0                                  NaN
                             125000.0                                  NaN
                             150000.0                                  NaN
                             175000.0                                  NaN
                             200000.0                                  NaN
        Male                 0.0                                       1.0
...                                                                    ...
45 - 59 Male                 0.0                                       NaN
                             10000.0                                   NaN
                             25000.0                                   NaN
                             50000.0                                   NaN
                             75000.0                                   NaN
                             100000.0                                  NaN
                             125000.0                                  NaN
                             150000.0                                  NaN
                             175000.0                                  NaN
                             200000.0                                  NaN
60+     Female               0.0                                       NaN
                             10000.0                                   NaN
                             25000.0                                   NaN
                             50000.0                                   NaN
                             75000.0                                   NaN
                             100000.0                                  NaN
                             125000.0                                  NaN
                             150000.0                                  NaN
                             175000.0                                  NaN
                             200000.0                                  NaN
        Male                 0.0                                       NaN
                             10000.0                                   NaN
                             25000.0                                   NaN
                             50000.0                                   NaN
                             75000.0                                   NaN
                             100000.0                                  NaN
                             125000.0                                  NaN
                             150000.0                                  NaN
                             175000.0                                  NaN
                             200000.0                                  NaN

What is typically the main dish at your Thanksgiving dinner?  Other (please specify)  \
Age     What is your gender? int_income
18 - 29 Female               0.0                                                 NaN
                             10000.0                                             NaN
                             25000.0                                             1.0
                             50000.0                                             NaN
                             75000.0                                             NaN
                             100000.0                                            NaN
                             125000.0                                            NaN
                             150000.0                                            NaN
                             175000.0                                            NaN
                             200000.0                                            NaN
        Male                 0.0                                                 NaN
                             10000.0                                             NaN
                             25000.0                                             NaN
                             50000.0                                             NaN
                             75000.0                                             NaN
                             100000.0                                            NaN
                             125000.0                                            NaN
                             150000.0                                            NaN
                             200000.0                                            NaN
30 - 44 Female               0.0                                                 NaN
                             10000.0                                             1.0
                             25000.0                                             3.0
                             50000.0                                             1.0
                             75000.0                                             2.0
                             100000.0                                            NaN
                             125000.0                                            NaN
                             150000.0                                            NaN
                             175000.0                                            NaN
                             200000.0                                            NaN
        Male                 0.0                                                 NaN
...                                                                              ...
45 - 59 Male                 0.0                                                 NaN
                             10000.0                                             NaN
                             25000.0                                             NaN
                             50000.0                                             NaN
                             75000.0                                             NaN
                             100000.0                                            1.0
                             125000.0                                            2.0
                             150000.0                                            NaN
                             175000.0                                            2.0
                             200000.0                                            1.0
60+     Female               0.0                                                 NaN
                             10000.0                                             1.0
                             25000.0                                             1.0
                             50000.0                                             1.0
                             75000.0                                             1.0
                             100000.0                                            NaN
                             125000.0                                            NaN
                             150000.0                                            1.0
                             175000.0                                            NaN
                             200000.0                                            NaN
        Male                 0.0                                                 NaN
                             10000.0                                             NaN
                             25000.0                                             1.0
                             50000.0                                             NaN
                             75000.0                                             NaN
                             100000.0                                            1.0
                             125000.0                                            NaN
                             150000.0                                            NaN
                             175000.0                                            NaN
                             200000.0                                            1.0

What is typically the main dish at your Thanksgiving dinner?  Roast beef  \
Age     What is your gender? int_income
18 - 29 Female               0.0                                     NaN
                             10000.0                                 NaN
                             25000.0                                 NaN
                             50000.0                                 NaN
                             75000.0                                 NaN
                             100000.0                                NaN
                             125000.0                                NaN
                             150000.0                                NaN
                             175000.0                                NaN
                             200000.0                                NaN
        Male                 0.0                                     3.0
                             10000.0                                 NaN
                             25000.0                                 NaN
                             50000.0                                 NaN